% -------------------------------------------------------------------
%  Generated by MATLAB on 17-Feb-2024 18:11:46
%  MATLAB version: 9.12.0.2009381 (R2022a) Update 4
% -------------------------------------------------------------------
saveVarsMat = load('Assembly1_DataFile.mat');

smiData = saveVarsMat.smiData; % <1x1 struct> unsupported class at smiData.RigidTransform(1).ID

clear saveVarsMat;
